Migration/google auth
CatoffGaming/catoff-fitness-indexer pull request #39
Opened 2024-04-18 03:59 UTC by thomas21-jquerry

# Migration
## Description
Migration of Google login module done

## Purpose
Migration from express to nestJs

## Changes Made

- Added google fit module
- Implemented user updates queue
- Implemented aouth 
- JWT

## Testing

## Screenshots (if applicable):
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to change)

2024-04-20 07:50 UTC, priyam-anand commented on config/configuration.ts
> +    CLIENT_ID: process.env.CLIENT_ID,
@thomas21-jquerry 
We already have this env variable with the name of "GOOGLE_CLIENT_ID" and "GOOGLE_CLIENT_SECRET".
Please change this.

2024-04-20 07:50 UTC, priyam-anand commented on env/.env.sample
> +CLIENT_ID=
Same as above

2024-04-20 07:50 UTC, priyam-anand commented on package-lock.json
@thomas21-jquerry  Stick to using yarn. and remove this file

2024-04-20 07:50 UTC, priyam-anand commented on src/google/google.module.ts
> +  controllers: [GoogleUserController],
the controller is being used for auth endponts. It should not be declared in this module.
Rather make a new module called Auth and integration it with the google auth services.
@thomas21-jquerry

2024-04-20 07:50 UTC, priyam-anand commented on src/okto/okto.controller.ts
> +  @Post('set_pin')
stick to one pattern for naming, either use camelCase or snake case. Don't use both

2024-04-20 07:50 UTC, priyam-anand commented on src/okto/okto.controller.ts
> +    const userId = headers.UserID;
Stick to one pattern for fetching headers.
Either get headers directly from the Decorator or from Request. Don't do both. (refer line 18 in this file)
@thomas21-jquerry

2024-04-20 07:50 UTC, priyam-anand commented on src/okto/okto.service.ts
> +    private readonly OKTO_TECH_API_BASE_URL = 'https://sandbox-api.okto.tech/';
export this from a constant file

2024-04-20 07:50 UTC, priyam-anand commented on src/okto/okto.service.ts
> +    async processAuthenticationResponse(userId: number, responseData: any){
create an interface for "responseData", don't use "any" type as much as possible

2024-04-20 07:50 UTC, priyam-anand commented on src/okto/okto.service.ts
> +          throw error;
For services stick to the same pattern used in indexer ie. returning a data field and and error field.
Helps in layer wise error handeling.

2024-04-20 07:50 UTC, priyam-anand commented on src/okto/okto.service.ts
> +          const response = await axios.get(
dont' use axios directly. Use HttpService provided by nest js. Refer Indexer's code
@thomas21-jquerry

2024-04-20 07:50 UTC, priyam-anand commented on src/okto/okto.service.ts
> +          const userConfig =  await this.userConfigRepoService.get({where:{User:{UserID:userId}}});
do the formatting of codebase based on the given .prettierrc file before pushing any code @thomas21-jquerry

2024-04-20 07:50 UTC, priyam-anand commented on src/repo/user-config-repo.service.ts
> +  async signInHelper(
Rename this to something more relevant. Maybe call it findOrCreate etc @thomas21-jquerry

2024-04-20 07:50 UTC, priyam-anand commented on src/repo/user-config-repo.service.ts
> +      return userConfig;
stick to same pattern used in other functions for returning data and error @thomas21-jquerry

2024-04-20 07:50 UTC, priyam-anand commented on src/repo/user-repo.service.ts
> +  async signin(dataInfo: oauth2_v2.Schema$Userinfo, tokens: Auth.Credentials): Promise<[string, User]>{
Again, use better names

2024-04-20 07:50 UTC, priyam-anand commented on src/repo/user-repo.service.ts
> +          Credits: 500, // signup credits
move these initial credits to a constants file

2024-04-20 07:56 UTC, thomas21-jquerry commented on src/okto/okto.controller.ts
> +  @Post('set_pin')
Its what was already there in the current api server. if we change it here . we have to change the frontend

2024-04-20 07:57 UTC, thomas21-jquerry commented on src/okto/okto.service.ts
> +          const userConfig =  await this.userConfigRepoService.get({where:{User:{UserID:userId}}});
got it

2024-04-20 07:57 UTC, thomas21-jquerry commented on src/repo/user-config-repo.service.ts
> +  async signInHelper(
Understood

2024-04-20 08:00 UTC, thomas21-jquerry commented on config/configuration.ts
> +    CLIENT_ID: process.env.CLIENT_ID,
This is the Client id that aryaman was using. I dont know if the permissions and config are same for both of them

2024-04-20 08:00 UTC, thomas21-jquerry commented on package-lock.json
my bad

2024-04-23 08:59 UTC, priyam-anand requested changes

2024-04-23 08:59 UTC, priyam-anand commented on src/repo/user-repo.service.ts
> +      const JwtToken: string = jwt.sign(
move this out of the repo service. Repo service should interact with the db layer only. Nothing else

2024-04-23 08:59 UTC, priyam-anand commented on src/auth/auth.service.ts
> +      this.UserQueue.add('google-init', { userId });
Dont' hardcode the job name. Use from the constants file

2024-04-23 08:59 UTC, priyam-anand commented on src/auth/auth.service.ts
> +        data: {
define this interface for the return value

2024-04-23 08:59 UTC, priyam-anand commented on src/auth/auth.controller.ts
> +export class GoogleUserController {
Rename to AuthController and make the route to be '/auth'

2024-04-23 08:59 UTC, priyam-anand commented on src/auth/auth.module.ts
> +  controllers: [GoogleUserController],
Rename to AuthController

2024-04-23 08:59 UTC, priyam-anand commented on src/auth/auth.service.ts
> +        scope: [
Move these scopes to a constants file

2024-04-23 08:59 UTC, priyam-anand commented on src/auth/auth2Client.provider.ts
> +  //   private readonly oauth2Client: OAuth2Client;
remove this comment

2024-04-23 08:59 UTC, priyam-anand commented on src/okto/okto.controller.ts
> +      makeResponse(res, 500, false, `${error.stack}`, null);
don't return the entire error.stack as error message. just pass "error?.message"

2024-04-23 08:59 UTC, priyam-anand commented on src/okto/okto.controller.ts
> +  // @Post('setPin')
Don't push commented out code

2024-04-23 08:59 UTC, priyam-anand commented on src/okto/okto.controller.ts
> +        `${error.message}`,
add conditional state, ie. error?.message because sometimes error.message field can throw an error itself.

2024-04-23 08:59 UTC, priyam-anand commented on src/okto/okto.service.ts
> +  );
move these into "onApplicationBootstrap" function

2024-04-23 09:01 UTC, thomas21-jquerry commented on src/app/app.ts
> +  app.use(bodyParser.json({limit: '100mb'}));
should i reduce it to 50mb ?

2024-04-23 09:04 UTC, thomas21-jquerry commented on src/okto/okto.service.ts
> +        res = { status: 'new_user', message: 'Please set_pin API.' };
Its a long return type. I

2024-04-23 09:54 UTC, thomas21-jquerry commented on src/okto/okto.controller.ts
> +  // @Post('setPin')
We might need it later

2024-04-23 09:56 UTC, priyam-anand commented on src/app/app.ts
> +  app.use(bodyParser.json({limit: '100mb'}));
ideally this is not needed at all. Just remove for now.. we can add when needed.

2024-04-23 09:56 UTC, priyam-anand commented on src/okto/okto.controller.ts
> +  // @Post('setPin')
hmm okay.

2024-04-23 10:26 UTC, priyam-anand commented on src/okto/okto.service.ts
> +        res = {
okay, sorted

2024-04-23 11:01 UTC, merged